Recent work and about me sections
Rifat8080/Portfolio-site pull request #2
Opened 2023-04-27 17:30 UTC by Rifat8080

- added new 2 sections in mobile versions
- added different projects photos
- added logos of framewroks, skills and languages
- update css with display grid
- added html sections

2023-04-27 18:32 UTC, PinkMoon25 requested changes
Hi @Rifat8080 , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media1.giphy.com/media/31Q36EHJ7C5ZoIMw79/giphy.gif"/>

## Highlights
Linter checks :heavy_check_mark: 
github flow :heavy_check_mark: 
Flex and Grid :heavy_check_mark: 
Semantics :heavy_check_mark: 
follows figma template :heavy_check_mark: 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-27 18:32 UTC, PinkMoon25 commented on index.html
> +      <div class="jobs" id="jobs-id">
- [ ] Excellent work so far, you have done really well :clap: , I just have some suggestions to improve the design, so I think there is supposed to be a gap or spacing between the headline and works section currently it is missing that, please see :point_down: 
![image](https://user-images.githubusercontent.com/97521557/234956477-7c3976f9-d3a5-44b8-bd0f-9fd5d6ada9eb.png)
 figma design :point_down: 
![image](https://user-images.githubusercontent.com/97521557/234956657-7b605077-7062-446e-b7e4-cfd63bcc5fc4.png)

I think a margin-top of 80px should fix that :+1:

2023-04-27 18:32 UTC, PinkMoon25 commented on style.css
> +}
- [ ] For these tech tags in the project cards, please fix the color which should be `#3A4A42` , also fix the color of the project card's title i.e. 'Multi-Post_stories' 
![image](https://user-images.githubusercontent.com/97521557/234957797-8967e59e-704c-49c1-9803-7668c12660b7.png)
 figma :point_down: 
![image](https://user-images.githubusercontent.com/97521557/234957932-5b99d960-0bf5-4ebe-be6d-48bd13052b02.png)

2023-04-27 18:32 UTC, PinkMoon25 commented on index.html
> +          <button type="button" class="btn-showup">See Project</button>
- [ ] Please implement the button interactions for all your buttons like :point_down: 
from figma 
![image](https://user-images.githubusercontent.com/97521557/234958364-14c5158f-4b02-484a-8595-6e741ba59cd7.png)

2023-04-28 08:55 UTC, LionRouge1 approved these changes
Hi @Rifat8080, 

# STATUS: APPROVED! 🥇 💯 
Your project is complete! There is nothing else to say other than... it's time to merge it :shipit:

![done](https://media.giphy.com/media/a5llhdWKMOIfneMCpB/giphy.gif)

Good luck! 🎉 


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

2023-04-28 09:06 UTC, merged