Conversion to Desktop version
Rifat8080/Portfolio-site pull request #4
Opened 2023-05-03 14:32 UTC by Rifat8080

- Added media query @768 px 
- Customized all elements according to size and colors for desktop version
- Customize submission form according to desktop version

2023-05-03 16:47 UTC, bobb-Rob requested changes
## STATUS: CHANGES REQUIRED ♻️
Hi @Rifat8080, 

Good job so far! 👏👏👏 
There are some issues that you still need to work on to go to the next project but you are almost there!  😃 
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>
![](https://camo.githubusercontent.com/34482800e1b92cb79ddca06edb4051edc407cb190f896e1e949e596aa9073851/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f556461535559436c723932636a57706556782f67697068792e676966)

## Highlights
✅ No Linter error
✅ Correct use of GitHub flow
✅ Very descriptive Pull Request(PR)

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-03 16:47 UTC, bobb-Rob commented on index.html
> +                    </li>
- [ ] The contact section on the desktop lacks left and right padding as seen in the Figma design. Please fix this.

#### Your design
![image](https://user-images.githubusercontent.com/84156714/235982310-bb641995-463e-4104-9a74-605e0d86a9af.png)

#### Figma Design
![image](https://user-images.githubusercontent.com/84156714/235982664-c473aa05-e741-4c6c-a69d-070a30dec083.png)

2023-05-03 16:47 UTC, bobb-Rob commented on index.html
> +      </div>
- [ ] The green bar is not visible in the desktop design as observed in the Figma Design. Kindly remove it

Your work
![image](https://user-images.githubusercontent.com/84156714/235983139-54ace253-836a-4492-bb5c-d6e472402199.png)

Figma Design
![image](https://user-images.githubusercontent.com/84156714/235983266-667e3770-ab27-4123-a98a-4e5f7d740366.png)

2023-05-03 16:47 UTC, bobb-Rob commented on index.html
> +      </div>
- [ ] Your desktop view looks very good but the mobile view does not look good any longer. Kindly ensure that the your app on mobile still has proper margin, padding, and element in the right position.

![image](https://user-images.githubusercontent.com/84156714/235983734-21cb412d-3122-41c1-b0d5-2ad2cf1e8eea.png)

- [ ] Please go through all the sections and ensure that they look good on mobile view as well. I noticed that your contact section is scattered in mobile view.

![image](https://user-images.githubusercontent.com/84156714/235984392-1d678e8d-c0b0-4746-9c4b-3d9eb5fef1f9.png)

2023-05-04 09:21 UTC, levy002 approved these changes
## Hello @Rifat8080 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![](https://media.giphy.com/media/jJQC2puVZpTMO4vUs0/giphy.gif)

## Highlights
- No linter error :heavy_check_mark: 
- Good UI :heavy_check_mark: 

## Status: APPROVED :fire:  :fire: 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-04 11:54 UTC, merged