Popup window
Rifat8080/Portfolio-site pull request #9
Opened 2023-05-17 10:56 UTC by Rifat8080

- Added popup modal
- added new css style file for modal css
- added javascript for modal functioning
- added linters properly

2023-05-17 11:56 UTC, AbelG101 commented on popup.css
> +  }
- [ ] Please make sure you follow the given Figma design when implementing the button styling here as the width of the button is causing the text to break. please make sure to fix that. ✔
- Here's how it looks:
  ![image](https://github.com/Rifat8080/Portfolio-site/assets/104968236/8910f50f-86d9-4ab5-90dc-4077f13ebbe5)
- [ ] Also please make sure you implement the `hover` & `active` states of the button as shown in the below Figma design 👇
  ![firefox_kz6PEcoelc](https://github.com/Rifat8080/Portfolio-site/assets/104968236/fb1a7eb6-432a-49e2-acad-533d9c487736)

2023-05-17 11:59 UTC, AbelG101 commented on popup.css
> +}
- [ ] [OTPIONAL] It'd be better if you can center the popup vertically to the screen for a better UX 
- Here's how it looks:
  ![image](https://github.com/Rifat8080/Portfolio-site/assets/104968236/365cfaa7-23bc-407e-97a2-1a04be082646)

2023-05-17 20:54 UTC, franclobo requested changes
Hi @Rifat8080, 

# ♻️ Required Changes ♻️

![soClose](https://github.com/Rifat8080/Portfolio-site/assets/58642949/fe0d55cc-4ab8-40a2-ac4c-cef3e48d5ceb)

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights

- No linter errors ✔️
- Descriptive PR ✔️
- Correct Github flow ✔️ 
- Dynamic webpage ✔️

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-17 20:54 UTC, franclobo commented on index.html
> +    </div> -->
- [ ] Well done using JavaScript to populate this section as requested by the previous CR. Please 🙏🏽 remove the unused code for clean code and good practices of HTML & CSS, we use the comments to describe what the code does to help other programmers to read our code.

2023-05-18 07:52 UTC, andersonlebon approved these changes
## Hi @Rifat8080 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![nodding-yes](https://user-images.githubusercontent.com/65068771/143095390-344d1cb0-b853-4b91-8662-5d9049dc9e60.gif)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question `@andersonlebon` so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-18 07:57 UTC, merged